# Generated by Django 2.1.4 on 2018-12-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название жанра')),
                ('description', models.TextField(blank=True, verbose_name='описание жанра')),
            ],
        ),
        migrations.CreateModel(
            name='MusicStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название стиля')),
                ('description', models.TextField(blank=True, verbose_name='описание стиля')),
            ],
        ),
    ]
