# Generated by Django 2.1.4 on 2018-12-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_genres_musicstyles'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicstyles',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Genres'),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Genres'),
        ),
        migrations.AddField(
            model_name='product',
            name='music_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.MusicStyles'),
        ),
    ]
